name: Test

on:
  workflow_dispatch:

jobs:
  test:
    permissions:
      actions: read
      contents: write

    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Test 1
        run: |
          curl -vv --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' 'https://api.github.com/installation/repositories'